version: '3.8'

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
      - chromadb
      - ollama
    environment:
      OLLAMA_BASE_URL: http://ollama:11434
      MONGO_URL: mongodb://mongodb:27017/

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - mongodb

  chromadb:
    image: ghcr.io/chroma-core/chroma:latest
    ports:
      - "8000:8000"

  ollama:
    build:
      context: .
      dockerfile: Dockerfile.ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama




volumes:
  ollama:
